In [1]:
from network_temp import *
import numpy as np

In [2]:
my_model = DAGMMnet([10, 1], [10, 1], 10)

In [19]:
# raw_data = np.load('./data.npy')
# data_set = tf.data.Dataset.from_tensor_slices(raw_data.astype('float32')).shuffle(60000).batch(64)
# test_data = list(data_set.as_numpy_iterator())

In [ ]:
# z = my_model.compress_net.encoder(raw_data.astype('float32'))
# gamma = my_model.estimate_net(z)
# gmm_output = GMM(my_model.n_component, z, gamma)
# loss_1 = my_model.compress_net.compute_loss(raw_data.astype('float32'))
# loss_2 = gmm_output.energy_loss(z)
# loss_3 = gmm_output.diag_loss()

In [3]:
raw_data = np.load('./data.npy')
hidden = np.load('./hidden.npy')
optimizer = tf.keras.optimizers.Adam()
data_set = tf.data.Dataset.from_tensor_slices(raw_data.astype('float32')).shuffle(60000).batch(256)
train(data_set, my_model, 55, optimizer)

Time for epoch 1 is 3.7038609981536865 sec
Loss: 10.349642753601074
Time for epoch 2 is 1.7426187992095947 sec
Loss: 6.797159671783447
Time for epoch 3 is 1.667452096939087 sec
Loss: 4.734500885009766
Time for epoch 4 is 1.6533734798431396 sec
Loss: 3.285245895385742
Time for epoch 5 is 1.6880860328674316 sec
Loss: 2.3154280185699463
Time for epoch 6 is 1.638641595840454 sec
Loss: 1.74616539478302
Time for epoch 7 is 1.6478726863861084 sec
Loss: 1.4319902658462524
Time for epoch 8 is 1.6147253513336182 sec
Loss: 1.2572752237319946
Time for epoch 9 is 1.6059072017669678 sec
Loss: 1.1474117040634155
Time for epoch 10 is 1.7951042652130127 sec
Loss: 1.051720380783081
Time for epoch 11 is 1.7653183937072754 sec
Loss: 0.9461291432380676
Time for epoch 12 is 1.6474804878234863 sec
Loss: 0.826828122138977
Time for epoch 13 is 1.6671721935272217 sec
Loss: 0.7030162215232849
Time for epoch 14 is 1.7838678359985352 sec
Loss: 0.5835632085800171
Time for epoch 15 is 1.5979375839233398 sec
Loss: 0.

In [4]:
train(data_set, my_model, 50, optimizer)

Time for epoch 1 is 3.5282483100891113 sec
Loss: 20.390352249145508
Time for epoch 2 is 3.5711042881011963 sec
Loss: 20.39023208618164
Time for epoch 3 is 3.5658836364746094 sec
Loss: 20.271377563476562
Time for epoch 4 is 3.637331962585449 sec
Loss: 20.2530460357666
Time for epoch 5 is 3.6395559310913086 sec
Loss: 20.305356979370117
Time for epoch 6 is 2.7921524047851562 sec
Loss: 20.19831085205078
Time for epoch 7 is 2.2343411445617676 sec
Loss: 20.167314529418945
Time for epoch 8 is 2.209611654281616 sec
Loss: 20.087675094604492
Time for epoch 9 is 2.207282304763794 sec
Loss: 20.08258628845215
Time for epoch 10 is 2.2033913135528564 sec
Loss: 19.94313621520996
Time for epoch 11 is 2.2117671966552734 sec
Loss: 19.831632614135742
Time for epoch 12 is 2.2074084281921387 sec
Loss: 19.574953079223633
Time for epoch 13 is 2.2034571170806885 sec
Loss: 19.218585968017578
Time for epoch 14 is 2.2185938358306885 sec
Loss: 18.67519760131836
Time for epoch 15 is 2.1873507499694824 sec
Loss: 17.

In [4]:
result, z = my_model(raw_data)
#  如果要使用predict，需要重新设置batchsize
#  result_, z_ = my_model.predict(raw_data)


If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.



In [5]:
logit = np.exp(-result.numpy())

In [6]:
logit[:50000].mean()

0.86130553

In [7]:
logit[50000:].mean()

0.14636621

In [12]:
z = my_model.compress_net(raw_data)
gamma = my_model.estimate_net(z)
gmm_output = GMM(z, gamma)


If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.



In [15]:
z_new = my_model.compress_net.decoder(my_model.compress_net.encoder(raw_data))

In [1]:
import tensorflow as tf

In [19]:
gmm_output.sigma

<tf.Tensor: shape=(1, 3, 3), dtype=float32, numpy=
array([[[ 1.3899577 , -0.15162157,  0.11579624],
        [-0.15162157,  3.613577  , -0.3563622 ],
        [ 0.11579624, -0.3563622 ,  0.2695724 ]]], dtype=float32)>

In [20]:
gmm_output.mu

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[0.7546778 , 0.31944233, 0.84785765]], dtype=float32)>